// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjhnoucbrdheuhwbzxif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaG5vdWNicmRoZXVod2J6eGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTExNzcsImV4cCI6MjA3MjA4NzE3N30.-sUsmpqQ24RY5C5MB8EijPnMir2KSpkpPfNTPuV5sr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});